[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "ds-test/=lib/ds-test/src/",
    "forge-std/=lib/forge-std/src/",
    "erc4626-tests/=lib/openzeppelin-contracts/lib/erc4626-tests/",
    "halmos-cheatcodes/=lib/openzeppelin-contracts/lib/halmos-cheatcodes/src/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/",
    "@pythnetwork/pyth-sdk-solidity/=node_modules/@pythnetwork/pyth-sdk-solidity",
    "@pythnetwork/entropy-sdk-solidity/=node_modules/@pythnetwork/entropy-sdk-solidity",
]
solc_version = "0.8.20"

# Fork testing configuration
[rpc_endpoints]
spicy = "${SPICY_RPC_URL}"

[etherscan]
spicy = { key = "${ETHERSCAN_API_KEY}", url = "https://api.routescan.io/v2/network/testnet/evm/88882/etherscan" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
